### ISSUE TITLE
Need more info in log

### ISSUE THREAD

**Issue by MarkSwanson** [dwrensha/capnpc-rust#10]
capnpc-rust was calling panic!(), but I couldn't see what file it was trying to open.
I think this patch will help others.

$ git diff
diff --git a/src/codegen.rs b/src/codegen.rs
index 16c9be7..93c8f11 100644
--- a/src/codegen.rs
+++ b/src/codegen.rs
@@ -1596,7 +1596,7 @@ pub fn main<T : ::capnp::io::InputStream>(mut inp : T) -> ::std::io::Result<()>
                 use std::io::Write;
                 try!(writer.write_all(text.as_bytes()));
             }
-            Err(e) => {panic!("could not open file for writing: {}", e)}
+            Err(e) => {panic!("could not open file {:?} for writing: {}", filepath, e)}
         }
     }
     Ok(())

**Comment by dwrensha** [comment]
Good point! Fixed in https://github.com/dwrensha/capnpc-rust/commit/83720564c7e635dc626319e0cfae0d7667d89f72.
