### ISSUE TITLE
Porting codegen to use syntex_syntax (ie rustc's libsyntax)

### ISSUE THREAD

**Issue by kamalmarhubi** [dwrensha/capnpc-rust#13]
I've been looking around for someting rusty and capnp-y to do to get to know both better. I saw that capnpc-rust is producing output by interpolating and concatenating strings. I also saw that [syntex_syntax] makes rustc's [libsyntax] available through cargo.

Any interest in this port?

[syntex_syntax]: https://crates.io/crates/syntex_syntax
[libsyntax]: https://doc.rust-lang.org/syntax/

**Comment by dwrensha** [comment]
Hi Kamal!

I suppose some benefits that libsyntax might provide are:
  1. The ability to avoid an extra code generation step (I think this is what @cmr was hinting at in https://github.com/dwrensha/capnproto-rust/issues/11).
  2. Extra static error checking.
  3. Nice pretty printing.

Am I missing anything? 

Cargo's support for code generation in [build scripts](http://doc.crates.io/build-script.html) lessens the weight of (1). The other benefits would be nice to have, but it seems like using libsyntax to achieve them would bring a significant cost in terms of verbosity. 

It also appears that syntex has not been maintained for the past two months, so you'd first need to bring it up to date.

Perhaps I could interest you in taking on some other project relating to capnproto-rust? :)

Two things that would be really cool to support are [generics](https://capnproto.org/language.html#generic-types) and a [dynamic API](https://capnproto.org/cxx.html#dynamic-reflection). I think that the key to implementing both of these features will be to port the [schema](https://github.com/sandstorm-io/capnproto/blob/master/c%2B%2B/src/capnp/schema.h) and [schema-loader](https://github.com/sandstorm-io/capnproto/blob/master/c%2B%2B/src/capnp/schema-loader.h) implementations from capnproto-c++.

Another goal of mine is to eliminate our uses of `unsafe` in the `capnp` runtime library. Last I counted, there were something like 160 such uses. We should be able to get that down to zero without paying too much performance penalty.

Also, now that libgreen is dead, we [need to figure out a better concurrency story](https://github.com/dwrensha/capnp-rpc-rust/issues/5) for capnp-rpc-rust, possibly using [mio](https://github.com/carllerche/mio).

Or, lest these biggish projects scare you away, you could get your feet wet by fixing a smallish bug such as https://github.com/dwrensha/capnproto-rust/issues/31. And that reminds that yet another fun project might be to try fuzz testing capnproto-rust with [American Fuzzy Lop](https://github.com/kmcallister/afl.rs).

**Comment by kamalmarhubi** [comment]
++features, ++security are definitely fine with me. I hadn't looked too much into the AST-generation code to decide if it had value; I just don't like mashing strings together. I'll take a look around!

**Comment by kamalmarhubi** [comment]
Closing this since it sounds like you don't consider it terribly desirable. I 'd also prefer not to have to take on maintainership of another project to get this done.
