### ISSUE TITLE
Premature EOF Error when running the example.

### ISSUE THREAD

**Issue by zorend** [dwrensha/capnpc-rust#27]
Hi, thanks for the great work. I'm having this issue when running the example on windows, rust nightly 01/01/2016
```
Process didn't exit successfully: `D:\Projects\lobby-rs\target\debug\build\lobby-rs-c7d7991a1fa58573\build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Custom(Custom { kind: Other, error: StringError("Premature EOF") }) })', ../src/libcore\result.rs:688
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Custom(Custom { kind: Other, error: StringError("Premature EOF") }) })', ../src/libcore\result.rs:688
```

EDIT: this issue appears when you have capnp in the PATH, in my case it was due to using "cargo install capnpc"

**Comment by dwrensha** [comment]
Hi! Thanks for the report.

Which example? Do you get the error with `cargo build` or just with `cargo run`?

Unfortunately, I don't have an easy way to try things out on Windows, so it may be difficult for me to debug this.

**Comment by zorend** [comment]
Hi, thanks for the reply. it is the addressbook example, I tried it on linux too, the previous mentioned error seems to be because I added capnp to path, I removed it and now I'm having another error on windows and linux
```
hread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 2, message: "The system cannot find the file specified." } })', ../src/libcore\result.rs:688
```
I tried it on fresh linux installation using cargo build and cargo run. if it works for you can you please tell me which rust version. I'm using the latest nightly. Thanks

**Comment by dwrensha** [comment]
It works for me on stable, beta, and nightly.

Is the `capnp` executable installed on your system? As noted in #25, we currently do not display a very helpful error message when that is the case.

**Comment by zorend** [comment]
That was my problem, Thank you very much

**Comment by dwrensha** [comment]
Realized I may have closed this prematurely. Please let me know if you're still hitting problems on Windows, or with anything else.
