### ISSUE TITLE
Add #![allow(dead_code)] in generated *.rs files

### ISSUE THREAD

**Issue by hicqu** [dwrensha/capnpc-rust#34]
There are a lot of **method is never used: `Something`** when `cargo build`.

So, I think we need **#![allow(dead_code)]**. What do you think?

**Comment by dwrensha** [comment]
Unfortunately, putting `#![allow(dead_code)]` at the top of generated files would interfere with `include!()`: https://github.com/rust-lang/rust/issues/18810

We could put `#[allow(dead_code)]` on every generated item, but that seems ugly.

So, I recommend that you add the `#[allow(dead_code)]` attribute yourself, at the location in the code where you `include!()` the generated code.

**Comment by hicqu** [comment]
OK, I will try do that in build.rs. Thank you!
