### ISSUE TITLE
When a schema is in a subdirectory generate fails to create output directory

### ISSUE THREAD

**Issue by griff** [dwrensha/capnpc-rust#35]
When a capnp file is in a directory the generator does not correctly create the subdirectory in OUT.

In short this will fail:

```
extern crate capnpc;

fn main() {
    ::capnpc::CompilerCommand::new()
        .file("schema/process.capnp")
        .run()
        .expect("compiling");
}
```

The reason it fails is that the code in `codegen.rs` creates the directory $PWD/schema instead of the correct $OUT/schema.

**Comment by dwrensha** [comment]
Confirmed that there is a bug here.

Until this gets fixed, I recommend adding a `.src_prefix()` line, like this:

```rust
   ::capnpc::CompilerCommand::new()
        .file("schema/process.capnp")
        .src_prefix("schema")
        .run()
        .expect("compiling");
```

Then the generated files go directly into `$OUT_DIR`.

**Comment by dwrensha** [comment]
Fixed in https://github.com/dwrensha/capnpc-rust/commit/c692b5a12e4c03ad19ca55db7041d84adbd540dd.

Thanks for the report!
