### ISSUE TITLE
Translate the comments into the Rust documentation?

### ISSUE THREAD

**Issue by ArtemGr** [dwrensha/capnpc-rust#4]
I've just found that rustdoc can easily generate the docummentation for the code produced by the Cap'n Proto compiler. That's very useful, especially for a beginner like me who isn't familiar with the conventions used in the generated stubs.

One thing I'd like to see is the `#` comments documentation from the Cap'n Proto scheme files copied into rustdoc `///` comments so that the generated rustdoc documentation contains the explanations from the schema.

**Comment by dwrensha** [comment]
I agree that forwarding schema documentation to rustdoc would be useful. Unfortunately the Cap'n Proto schema compiler currently does not forward any information about comments. By the time the `capnpc-rust` plugin sees a schema, the comments are gone.

This has been discussed on the capnproto mailing list, most recently (I believe) here: https://groups.google.com/forum/#!msg/capnproto/_8SrDrNjX2Q/lu__XvMsv7UJ

**Comment by ArtemGr** [comment]
Should wait for Kenton Varda to implement it then. Would you prefer to close the RFE for now?

**Comment by dwrensha** [comment]
Yeah, let's close this here until there's something we can do on this end.
