### ISSUE TITLE
The example just hangs

### ISSUE THREAD

**Issue by bfops** [dwrensha/capnpc-rust#7]
For some reason, running the example just hangs on `p.wait()`. Running the commands manually doesn't seem to cause a problem. I'm on `rustc 1.0.0-nightly (2fc8b1e7c 2015-03-07) (built 2015-03-08)`.

**Comment by bfops** [comment]
Ah actually, manually running the commands gives errors for:

```
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("addressbook");
```

Removing those makes it work..

**Comment by dwrensha** [comment]
Ouch. There was a bug where a premature EOF would cause an infinite loop. Fixed here: https://github.com/dwrensha/capnproto-rust/commit/ba62726d0566d9b976771ec5c30decc83c4c680f

Now you should get an error indicating that the import failed.

**Comment by bfops** [comment]
Oh, heh. Works perfectly now, thanks!
