### ISSUE TITLE
File creation errors when the .capnp file is not in the current directory.

### ISSUE THREAD

**Issue by bfops** [dwrensha/capnpc-rust#8]
In the example, the .capnp file is in the same directoy as `build.rs` and `Cargo.toml`. Moving it to `src/addressbook.capnp` causes "error writing file" errors. It looks like [this line](https://github.com/dwrensha/capnpc-rust/blob/cc173e503b222bc4ce5d36a5d776391aefa6b56d/src/codegen.rs#L1562) gets a string like `src/addressbook.capnp` instead of `addressbook.capnp`. This might be an issue with capnproto-rust.

**Comment by dwrensha** [comment]
Did you update `build.rs` when you tried this? It works for me if I change it to this:

```
#![feature(path)]

extern crate capnpc;

fn main() {
    ::capnpc::compile(&::std::path::Path::new("src"),
                      &[::std::path::Path::new("src/addressbook.capnp")]).unwrap();
}
```

**Comment by bfops** [comment]
Oh yeah that's my mistake, I still had `Path::new(".")` for the first path; for some reason, I thought it had to do with the output directory and not the source directory.
