### ISSUE TITLE
Hard-coded /bin/cat

### ISSUE THREAD

**Issue by fread2281** [dwrensha/capnpc-rust#9]
Not all systems have `cat` in `/bin`, specifically this fails on nixos.

**Comment by dwrensha** [comment]
Would it work for you if it got the absolute path of `cat` by running `which cat`?

P.S. I added a new "-o -" flag to `capnp -compile`, so in the future we won't need `cat` https://github.com/sandstorm-io/capnproto/pull/190

**Comment by fread2281** [comment]
Yes, that would work, for now I've edited the hard-coded path.

`-o -` in capnp sounds like the better solution

**Comment by dwrensha** [comment]
Addressed in https://github.com/dwrensha/capnpc-rust/commit/d2b81e040abd936fdaa70883965ccc850343c5ab.
